SLING-11609: Provide doGetWithRetry methods in Sling Testing Clients
apache/sling-org-apache-sling-testing-clients pull request #38
Opened 2022-10-04 13:58 UTC by nscendoni

In several situations during IT Tests development we need to retry doGet method until some assertion are verified.

I propose in the attached pull request an implementation and test for new methods doGetWithRetry

2022-10-04 15:53 UTC, joerghoh requested changes

2022-10-04 15:53 UTC, joerghoh commented on src/main/java/org/apache/sling/testing/clients/AbstractSlingClient.java
> +            throw new TestingValidationException(e.getMessage(), e);
is the TestingValidationException really the right exception to throw here? It would suggest that there was a result which did not match the expectation (e.g. a 200 instead of a 404).
I would suggest to rather throw a TestingIOException,

2022-10-04 15:53 UTC, joerghoh commented on src/main/java/org/apache/sling/testing/clients/AbstractSlingClient.java
> +                        throw new TestingValidationException(e.getMessage(), e);
Please throw the TestingValidationException only when Assertion failed.

2022-10-04 16:09 UTC, nscendoni commented on src/main/java/org/apache/sling/testing/clients/AbstractSlingClient.java
> +            throw new TestingValidationException(e.getMessage(), e);
Sonarclub check also reported that I should not catch and raise InterruptedException. I'm not catching them anymore. Is that ok?

2022-10-04 16:15 UTC, nscendoni commented on src/main/java/org/apache/sling/testing/clients/AbstractSlingClient.java
> +                        throw new TestingValidationException(e.getMessage(), e);
I'm not catching TimeoutException and  InterruptedException  anymore.

2022-10-05 07:30 UTC, anchela reviewed
hi @nscendoni , just added a few minor nitpicking comments..... for the rest of the super minor stuff see the patch....

2022-10-05 07:30 UTC, anchela commented on src/main/java/org/apache/sling/testing/clients/AbstractSlingClient.java
> +            private int lastStatusCode = -1;
i believe 'lastStatusCode' could be a local field in the method

2022-10-05 07:30 UTC, anchela commented on src/main/java/org/apache/sling/testing/clients/AbstractSlingClient.java
> +        private SlingHttpResponse response;
inconsistent indention.... (being picky)

2022-10-05 07:30 UTC, anchela commented on src/main/java/org/apache/sling/testing/clients/AbstractSlingClient.java
> +            for (int count=0; count<expectedStatus.length; count++) {
that could imho be using the enhanced for-loop: `for (int status : expectedStatus)`

2022-10-05 10:32 UTC, nscendoni commented
@enapps-enorman Thanks for the suggestion. awaitility is a very good good library I didn't know.
Unfortunately I had to implement anyway a private class in order to return `SlingHttpResponse`

@joerghoh: Exceptions now are managed by awaitility
@anchela: Thanks for the review. I incorporated the suggestions on the new code.

2022-10-05 13:10 UTC, anchela approved these changes
@nscendoni , the changes look good to me. but take it with a grain of salt as i am not particularly familiar with the testing clients code base.

2022-10-05 17:56 UTC, enapps-enorman commented
@nscendoni If I am not mistaken, I believe using Awaitility apis along with the existing SlingClient#doGet call could accomplish the same thing without introducing any new code into the Sling Testing Clients.

For example, something like this:
`    @Test
    public void testDoGetWithRetry() throws ClientException, InterruptedException, TimeoutException {
        SlingClient c = new SlingClient(httpServer.getURI(), "user", "pass");

        Awaitility.await("doGet until expectedStatus and Assertions are satisfied")
            .atMost(Duration.ofSeconds(1000))
            .pollInterval(Duration.ofMillis(100))
            .ignoreExceptionsInstanceOf(ClientException.class)
            .until(() -> {
                SlingHttpResponse response = c.doGet("/", 200);
                return SUCCESS_RESPONSE.equals(response.getContent());
            });
    }
`
Does that make sense?  Do you have other requirements that need something else?

2022-10-06 15:40 UTC, nscendoni commented
@enapps-enorman Yes, I can use Awaitility without modifying sling-testing-clients and the code is compact and clean. 
You can either close this pull request or merge it if you think this could be useful to other people.

2022-10-06 18:04 UTC, enapps-enorman commented
> I wouldn't mind if we keep this functionality, even if it is just a thin wrapper around `Awaitility`.

@joerghoh I won't stand in the way of that since this just just for testing, but it seems redundant and the solution is incomplete since it is only handling the 'GET' request scenario.  The same problem could arise for a head, post, put, delete, patch or stream action as well.  The solution I proposed would handle all other scenarios the same way.

Perhaps a simple example in the [readme](https://github.com/apache/sling-org-apache-sling-testing-clients/blob/master/README.md) FAQ would suffice?

2022-10-06 19:39 UTC, joerghoh commented
@enapps-enorman It's fine for me if we move the example you have given above into the readme. It's just that I don't want to loose that snippet here in the github PR section.

@nscendoni would you mind to change the PR and add it to the README instead?

2022-10-11 07:05 UTC, nscendoni commented
Hi @joerghoh
I reverted my changes and added a small section in the Readme about how to retry HTTP Requests including the coded snippet provided by @enapps-enorman

2024-01-15 08:46 UTC, dulvac approved these changes

2024-01-15 08:47 UTC, merged