SLING-XXX: Set more descriptive User-Agent for SlingClients
apache/sling-org-apache-sling-testing-clients pull request #41
Opened 2022-11-16 12:24 UTC by Kronnox

Instead of the current User-Agent `JAVA` that is used on all SlingClient requests a more descriptive one (`sling-testing-client/<version>`) is used instead.

Furthermore functionality for customising and changing the User-Agent is added as well. The User-Agent may be replaced or appended on a per test basis. This allows for both a more concise debugging experience as well as test-cases in which a specific User-Agent needs to be specified.

An easy to use developer interface will be provided in the form of JUnit rules later on.

2022-11-16 14:51 UTC, bdelacretaz commented on src/main/java/org/apache/sling/testing/Constants.java
> +    public static final String SLING_CLIENT_USERAGENT_TITLE = "sling-testing-client";
I think we should not change the current default value which is "Java" - existing tests might break if we change it.

2022-11-16 14:53 UTC, joerghoh commented on src/main/java/org/apache/sling/testing/Constants.java
> +    public static final String SLING_CLIENT_USERAGENT_TITLE = "sling-testing-client";
Tests or other processes around these tests, which rely on the default user agent to filter out requests from the tests?

2022-11-16 14:54 UTC, bdelacretaz commented on src/main/java/org/apache/sling/testing/clients/util/UserAgent.java
> +public class UserAgent {
I wonder if we need such a sophisticated way of managing user-agent values, just for tests...how about using just a String for the User-Agent? In the spirit of keeping things as simple as possible.

2022-11-16 14:55 UTC, bdelacretaz commented on src/test/java/org/apache/sling/testing/CustomUserAgentInterceptorTest.java
> +        SlingHttpResponse response = client.doGet(PATH, 200);
I think the tests would be more readable by factoring out the 3 get + check header lines in an `assertUserAgent`utility method.

2022-11-16 14:56 UTC, bdelacretaz commented
Thanks for this! I've made a few minor comments but it generally looks good to me.

2022-11-16 15:16 UTC, bdelacretaz commented on src/main/java/org/apache/sling/testing/Constants.java
> +    public static final String SLING_CLIENT_USERAGENT_TITLE = "sling-testing-client";
Both maybe? Anyway I think changing that default is risky and I don't see a good reason to change it.

2022-11-16 15:29 UTC, Kronnox commented on src/test/java/org/apache/sling/testing/CustomUserAgentInterceptorTest.java
> +        SlingHttpResponse response = client.doGet(PATH, 200);
I totally agree

2022-11-16 15:42 UTC, Kronnox commented on src/main/java/org/apache/sling/testing/Constants.java
> +    public static final String SLING_CLIENT_USERAGENT_TITLE = "sling-testing-client";
Let's discuss that.
The initial reasoning behind the proposal was users being confused with the `JAVA` agent since it's not really descriptive in any way and doesn't hint to where the requests are coming from. I agree on it being risky to change the default, when it comes to existing log-filters and such. Other test relying on these test to have a specific User-Agent sounds rather unlikely to me, but you're right; guess you can never be sure...

IMHO just leaving it as it is, isn't a good solution either. Do we have any option to leave it as is for current users and only include the change with new installations; some properties file or something? Anyways, I think this is rather a problem of communicating the change, than a technical limitation.

2022-11-16 16:17 UTC, joerghoh commented on src/main/java/org/apache/sling/testing/Constants.java
> +    public static final String SLING_CLIENT_USERAGENT_TITLE = "sling-testing-client";
Can we make it possible to override this default value with a custom value you can provide externally as a new default?

2022-11-16 16:33 UTC, Kronnox commented on src/main/java/org/apache/sling/testing/Constants.java
> +    public static final String SLING_CLIENT_USERAGENT_TITLE = "sling-testing-client";
Okay, i agree. I'll propose some changes for easy adjustment of the agent while keeping it backwards compatible per default

2022-11-17 16:31 UTC, joerghoh requested changes

2022-11-17 16:31 UTC, joerghoh commented on src/main/java/org/apache/sling/testing/Constants.java
> +
Please remove this unnecessary whitespace-change.

2022-11-17 16:31 UTC, joerghoh commented on src/main/java/org/apache/sling/testing/clients/SystemPropertiesConfig.java
> +    public static final String CLIENT_USERAGENT_TITLE = "client.useragent.title";
nitpick: I think that the useragent has a "name", and not a "title" :-)

2022-11-18 13:19 UTC, dulvac approved these changes
lgtm, Thank you for the changes!

2022-11-18 13:20 UTC, dulvac commented
@joerghoh, @bdelacretaz do you think this is ready to merge? I'd like to make a release of this.

2022-11-28 13:25 UTC, joerghoh approved these changes

2022-11-28 13:56 UTC, merged

2022-11-28 14:35 UTC, bdelacretaz commented
Thanks for merging this, sorry that I missed your previous message @dulvac 
And thanks @Kronnox for this contribution!